FROM tensorflow/tensorflow:1.3.0-gpu-py3
RUN pip install --upgrade pip 
RUN pip uninstall -y numpy
RUN pip install numpy==1.12 scipy==0.17.1 theano==0.8.2 scikit-learn==0.19.1
RUN pip install matplotlib==2.1.0
RUN pip install keras==2.0.6
RUN pip install librosa==0.5.1
RUN pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
RUN pip install https://github.com/dnouri/nolearn/archive/master.zip#egg=nolearn
RUN pip install pandas==0.20.3
RUN pip install munkres==1.0.7